### ISSUE TITLE
master installation bug

### ISSUE THREAD

**Issue by kingjr** [jovyan/pythreejs#97] opened 2017-05-11 19:35 UTC
Hi, 

I'm trying to install master on an ubuntu 16.10 with python 2.7 install with conda

`python setup.py develop`  or `install`

gives me the following error:

```
Installing build dependencies with npm.  This may take a while...

> jupyter-js-widgets@3.0.0-alpha.5 postinstall /home/jrking/git/pythreejs/js/node_modules/jupyter-js-widgets
> npm dedupe


> jupyter-threejs@0.3.0-alpha.0 prepublish /home/jrking/git/pythreejs/js
> webpack

/usr/bin/env: ‘node’: No such file or directory

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.8.0-49-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jupyter-threejs@0.3.0-alpha.0 prepublish: `webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jupyter-threejs@0.3.0-alpha.0 prepublish script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-threejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-threejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-threejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jrking/git/pythreejs/js/npm-debug.log
rebuilding js and css failed
missing files: ['/home/jrking/git/pythreejs/pythreejs/static/extension.js', '/home/jrking/git/pythreejs/pythreejs/static/index.js']
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    setup(**setup_args)
  File "/home/jrking/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/jrking/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/jrking/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/jrking/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 34, in run
  File "/home/jrking/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/develop.py", line 115, in install_for_development
  File "/home/jrking/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/jrking/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 47, in run
    raise e
subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
```

an idea of what I should do?

**Comment by vidartf** [comment] 2017-10-12 17:53
Can you verify the the latest changes to master fixes this?

**Comment by vidartf** [comment] 2017-10-27 14:00
Closing due to missing feedback. Will reopen if someone can reproduce with master.

**Closed by vidartf** 2017-10-27 14:00 UTC
