### ISSUE TITLE
Fails under IPython 3.1, cannot import widget_serialization

### ISSUE THREAD

**Issue by DavidPowell** [jovyan/pythreejs#13] opened 2015-04-17 03:41 UTC
From the comments near the imports at the top of `pythree.js`, it seems that pythreejs should work under IPython 3.x. However, it tries to import `widget_serialization`, which appears to only exist in the new Jupyter notebook.

Is this bug fixable, or do you intend to have the development version of the Jupyter notebook as a minimum dependency?

**Comment by cekees** [comment] 2015-05-12 17:57
Looks like you can roll back to 6a1919b4fb15159a51917de52eb5785d9d069df3 to use it with 3.1.

**Comment by jasongrout** [comment] 2015-05-15 19:12
Thanks, @cekees, and sorry, @DavidPowell that I didn't see this until now!  That's awesome you are using this.

I'd recommend rolling back to a previous version of pythreejs.  We aren't developing a ton of new features right now, so master is tracking Jupyter changes.

I'll (retroactively) make a release tag so that we know where compability with IPython 3.x ends.

**Comment by DavidPowell** [comment] 2015-05-16 12:47
@jasongrout Thanks for the update. Currently I'm not using pythreejs, just playing around with it. I was hoping that it would eventually make a nicely engineered replacement for my current bodge solution, as discussed previously on [ipython-dev](http://mail.scipy.org/pipermail/ipython-dev/2015-January/015731.html).

To serve as a full replacement, I would want static html output, which I believe is not (yet) supported. I'm not sure if the IPython widget serialisation introduced in 3.x makes this easier, or what we can expect on this front from the Jupyter notebook.

**Comment by jasongrout** [comment] 2015-05-16 14:04
I definitely want it to work in static HTML files.  To get this, we could have a way to persist widget state to the notebook, and then support in nbconvert to instantiate widgets.

**Comment by jasongrout** [comment] 2015-06-19 14:51
@DavidPowell - can you check to see if the master version works?  @SylvainCorlay suggested a simple fix to have backwards compatibility with IPython 3.x, which I implemented at https://github.com/jasongrout/pythreejs/commit/f06441dd477ff00ec23dc691cb8105a4a8e3632f

**Comment by cekees** [comment] 2015-06-19 17:43
I didn't get a chance to try it yet, sorry. Probably won't get to it til late next week.                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the Verizon Wireless 4G LTE network.                                                                                                                                                                                                                                         From: Jason GroutSent: Friday, June 19, 2015 3:51 PMTo: jasongrout/pythreejsReply To: jasongrout/pythreejsCc: Chris KeesSubject: Re: [pythreejs] Fails under IPython 3.1, cannot import widget_serialization (#13)@DavidPowell - can you check to see if the master version works?  @SylvainCorlay suggested a simple fix to have backwards compatibility with IPython 3.x, which I implemented at f06441d

—Reply to this email directly or view it on GitHub.

**Comment by jasongrout** [comment] 2015-06-19 20:43
Sure, thanks.  If you get a minute to check it, let me know and I'll close this issue.

**Comment by DavidPowell** [comment] 2015-06-22 00:06
@jasongrout - Running the example under IPython 3.1 and python 2.7, the first cell now executes with no import errors. However, the second cell just seems to freeze the kernel and not produce any output.

**Comment by jasongrout** [comment] 2015-06-22 15:51
Thanks for checking.  I also checked with a fresh Anaconda installation and IPython 3.1, and things seemed to work well. (the examples seemed to work as expected).  Did you clear your browser cache to make sure there wasn't old javascript being loaded?  (Did you also make sure that the current version of the javascript was installed?)

**Comment by DavidPowell** [comment] 2015-06-23 00:02
@jasongrout It's working fine with IPython 3.2 after I manually installed the nbextensions. Thanks for that.

It's been a while since I tried using pythreejs. I had a vague feeling that just running setup.py wasn't enough, but I didn't see any further instructions in README.md :-)

**Comment by jasongrout** [comment] 2015-06-23 02:26
Thanks for confirming that it works!

**Comment by cekees** [comment] 2015-07-21 16:54
Hi @jasongrout . Finally getting around to testing the master with ipython 3.1.0. I'm getting strange behavior on a debian machine. I see this in the javascript console
```
THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js
```
Does this look familiar? I don't get this error an ubuntu machine with a slightly older version of chrome as the browser.

**Comment by DavidPowell** [comment] 2015-07-22 01:07
@cekees The canvas renderer is used by three.js in cases where WebGL cannot be used, due to either the browser or the graphics drivers not supporting it. This was originally a core part of three.js, but at some point (I think in the past year or so), this was removed to the examples.

**Comment by jasongrout** [comment] 2015-07-22 02:33
Ah, so we'll need to copy it in from three.js and probably adjust our paths.  I'll do this soon.

**Comment by cekees** [comment] 2015-07-22 09:05
@tridelat this would seem to explain why I couldn't reproduce the issue on my laptop with chrome. I think you can verify just by going somewhere like this https://get.webgl.org/ to check that webgl is not working on your system.  Once the patch to pythreejs's included version of three.js goes in, then your system should work regardless!

**Comment by jasongrout** [comment] 2015-07-24 00:01
Thanks again.  This should be fixed by https://github.com/jasongrout/pythreejs/commit/e32996a6e284864a1db90808d76d0a946aa4cc9f.  I'll push a new release to pypi soon.

**Comment by jasongrout** [comment] 2015-07-24 15:10
I pushed pythreejs 0.1.7 to pypi, which should contain a fix for the canvasrenderer problem.

**Comment by SylvainCorlay** [comment] 2015-09-13 15:59
Closing since it is fixed.

**Closed by SylvainCorlay** 2015-09-13 15:59 UTC
